version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: mentoring-db
    restart: always
    environment:
      POSTGRES_USER: mentoring_user
      POSTGRES_PASSWORD: mentoring_password
      POSTGRES_DB: mentoring_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
